# Generated by Django 5.2.7 on 2025-10-11 23:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-start_date'], 'verbose_name': 'Campagne', 'verbose_name_plural': 'Campagnes'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contribution', 'verbose_name_plural': 'Contributions'},
        ),
        migrations.AlterModelOptions(
            name='entrepreneurprofile',
            options={'verbose_name': 'Profil entrepreneur', 'verbose_name_plural': 'Profils entrepreneurs'},
        ),
        migrations.AlterModelOptions(
            name='intermediairepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paiement intermédiaire', 'verbose_name_plural': 'Paiements intermédiaires'},
        ),
        migrations.AlterModelOptions(
            name='intermediaireprofile',
            options={'verbose_name': 'Profil intermédiaire', 'verbose_name_plural': 'Profils intermédiaires'},
        ),
        migrations.AlterModelOptions(
            name='investisseurprofile',
            options={'verbose_name': 'Profil investisseur', 'verbose_name_plural': 'Profils investisseurs'},
        ),
        migrations.AlterModelOptions(
            name='loancampaign',
            options={'ordering': ['-start_date'], 'verbose_name': 'Campagne de prêt', 'verbose_name_plural': 'Campagnes de prêt'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'Partenaire', 'verbose_name_plural': 'Partenaires'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='projectphoto',
            options={'ordering': ['created_at'], 'verbose_name': 'Photo de projet', 'verbose_name_plural': 'Photos de projet'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': "Membre de l'équipe", 'verbose_name_plural': "Membres de l'équipe"},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mise à jour', 'verbose_name_plural': 'Mises à jour'},
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de désactivation'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Compte désactivé'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant collecté'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Objectif financier'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ngo.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('paused', 'En pause'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='ngo.campaign', verbose_name='Campagne'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('donation', 'Don'), ('loan', 'Prêt')], max_length=10, verbose_name='Type de contribution'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contributor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du contributeur'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contributor_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du contributeur'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='investor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'investisseur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Investisseur'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='loan_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='ngo.loancampaign', verbose_name='Campagne de prêt'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mtn', 'MTN Mobile Money'), ('orange', 'Orange Mobile Money'), ('other', 'Autre')], default='paypal', max_length=50, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut du paiement'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de transaction'),
        ),
        migrations.AlterField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='commission_rate',
            field=models.FloatField(default=6.9, verbose_name='Taux de commission'),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='ngo.currency', verbose_name='Monnaie'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='countries/flags/', verbose_name='Drapeau'),
        ),
        migrations.AlterField(
            model_name='country',
            name='intermediaire_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais intermédiaire'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='country',
            name='project_submission_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de soumission de projet'),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='ngo.region', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate_to_usd',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='Taux de change USD'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Symbole'),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Expérience'),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='intermediairepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='intermediairepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='intermediairepayment',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngo.currency', verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='intermediairepayment',
            name='intermediaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediaire_payments', to=settings.AUTH_USER_MODEL, verbose_name='Intermédiaire'),
        ),
        migrations.AlterField(
            model_name='intermediairepayment',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='intermediaire/payments/', verbose_name='Preuve'),
        ),
        migrations.AlterField(
            model_name='intermediairepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='intermediaireprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='intermediaireprofile',
            name='subscription_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'abonnement"),
        ),
        migrations.AlterField(
            model_name='intermediaireprofile',
            name='subscription_paid',
            field=models.BooleanField(default=False, verbose_name='Abonnement payé'),
        ),
        migrations.AlterField(
            model_name='intermediaireprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intermediaire_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='intermediaireprofile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
        migrations.AlterField(
            model_name='investisseurprofile',
            name='capital_available',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Capital disponible'),
        ),
        migrations.AlterField(
            model_name='investisseurprofile',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='investisseurprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investisseur_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant collecté'),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_campaigns_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant cible'),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='loan_campaigns/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="Taux d'intérêt (%)"),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_campaigns', to='ngo.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='repayment_duration',
            field=models.PositiveIntegerField(help_text='Durée du remboursement en mois', verbose_name='Durée de remboursement (mois)'),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('paused', 'En pause'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='loancampaign',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('ngo', 'ONG / Association'), ('company', 'Entreprise privée'), ('gov', 'Institution publique'), ('individual', 'Partenaire individuel'), ('other', 'Autre')], default='other', max_length=50, verbose_name='Type de partenaire'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngo.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngo.currency', verbose_name='Monnaie'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_successful',
            field=models.BooleanField(default=False, verbose_name='Réussi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('project_submission', 'Soumission de projet'), ('intermediaire_subscription', 'Abonnement intermédiaire')], max_length=50, verbose_name='Type de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ngo.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='payments/proofs/', verbose_name='Preuve de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code de transaction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='projects', to='ngo.category', verbose_name='Catégories'),
        ),
        migrations.AlterField(
            model_name='project',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant collecté'),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='ngo.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date limite'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='entrepreneur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'entrepreneur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Entrepreneur'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Clôturé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='project',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant cible'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Légende'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='image',
            field=models.ImageField(upload_to='projects/photos/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ngo.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='region',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='ngo.campaign', verbose_name='Campagne'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, help_text='Image représentative de la récompense (facultative)', null=True, upload_to='rewards/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant minimum'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=150, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo du contributeur ou de la personne donnant le témoignage', null=True, upload_to='testimonials/photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='ngo.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='update',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='ngo.campaign', verbose_name='Campagne'),
        ),
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='update',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='updates/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='update',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Objet')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngo.project', verbose_name='Projet associé')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('project_validated', 'Projet validé'), ('project_rejected', 'Projet rejeté'), ('project_update', 'Mise à jour du projet'), ('new_comment', 'Nouveau commentaire'), ('campaign_contribution', 'Nouvelle contribution'), ('campaign_goal_reached', 'Objectif de campagne atteint'), ('campaign_update', 'Nouvelle mise à jour de campagne'), ('loan_contribution', 'Nouvelle contribution à un prêt'), ('loan_repayment', 'Remboursement reçu'), ('loan_completed', 'Campagne de prêt terminée'), ('intermediary_submission', 'Soumission par un intermédiaire'), ('payment_validated', 'Paiement validé'), ('payment_failed', 'Paiement échoué'), ('reward_earned', 'Récompense débloquée'), ('admin_message', 'Message administratif'), ('general', 'Notification générale')], default='general', max_length=50, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône Bootstrap ou Lucide (ex: bell, check-circle, gift)", max_length=50, verbose_name='Icône (optionnelle)')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('is_important', models.BooleanField(default=False, verbose_name='Importante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('related_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngo.campaign', verbose_name='Campagne liée')),
                ('related_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngo.contribution', verbose_name='Contribution liée')),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngo.loancampaign', verbose_name='Campagne de prêt liée')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngo.project', verbose_name='Projet lié')),
                ('related_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngo.reward', verbose_name='Récompense liée')),
                ('related_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngo.update', verbose_name='Mise à jour liée')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant demandé')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motif du retrait')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('paid', 'Payée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Entrepreneur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='ngo.project', verbose_name='Projet concerné')),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'verbose_name_plural': 'Demandes de retrait',
                'ordering': ['-created_at'],
            },
        ),
    ]
