# Generated by Django 5.2.7 on 2025-10-13 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_alter_campaign_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/entrepreneurs/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='intermediaireprofile',
            name='represented_entrepreneurs',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'entrepreneur'}, related_name='represented_by_intermediaires', to=settings.AUTH_USER_MODEL, verbose_name='Entrepreneurs représentés'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('message', 'Message'), ('notification', 'Notification'), ('update', 'Mise à jour')], default='message', max_length=30, verbose_name='Type de message'),
        ),
        migrations.AddField(
            model_name='message',
            name='preview_text',
            field=models.CharField(blank=True, help_text='Texte court pour aperçu dans les notifications.', max_length=120, verbose_name='Aperçu'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_avatar',
            field=models.ImageField(blank=True, help_text='Image affichée dans la liste de messages.', null=True, upload_to='avatars/messages/', verbose_name='Avatar de l’expéditeur'),
        ),
    ]
