# Generated by Django 5.2.7 on 2025-10-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_entrepreneurprofile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='bg_color',
            field=models.CharField(blank=True, default='bg-dark', help_text='Ex: bg-success, bg-danger, bg-warning', max_length=50, verbose_name='Couleur de fond icône'),
        ),
        migrations.AddField(
            model_name='notification',
            name='short_message',
            field=models.CharField(blank=True, help_text='Texte court pour dropdown / notification nav', max_length=255, verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom d'icône (ex: bell, calendar, settings)", max_length=50, verbose_name='Icône'),
        ),
    ]
