# Generated by Django 5.2.7 on 2025-10-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_notification_bg_color_notification_short_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investisseurprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/investisseurs/', verbose_name='Photo de profil'),
        ),
    ]
